config/routes.rb
Rails.application.routes.draw do
  root  to: 'home#index'
  resources :shipping_companies, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shipping_company.rb
class ShippingCompany < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/shipping_companies_controller.rb
class ShippingCompaniesController < ApplicationController
  def index
    @shipping_companies = ShippingCompany.all
  end

  def show
    @shipping_company = ShippingCompany.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Sistema de Entregas</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliverySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <nav>
      <%= link_to 'Tela Inicial', root_path %> |
      <%= link_to 'Transportadoras', shipping_companies_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/shipping_companies/index.html.erb
<h1>Transportadoras</h1>

<% if @shipping_companies.any? %>
  <% @shipping_companies.each do |sc| %>
    <p>Nome Fantasia: <%= link_to sc.trade_name, sc %></p>
  <% end %>
<% else %>
  <p>Nenhuma transportadora cadastrada.</p>
<% end %>

app/views/shipping_companies/show.html.erb
<h1>Transportadora: <%= @shipping_company.legal_name %></h1>
<h2><%= @shipping_company.trade_name %></h2>

<dl>
  <dt>Razão social:</dt>
  <dd><%= @shipping_company.legal_name %></dd>
  <dt>Nome fantasia:</dt>
  <dd><%= @shipping_company.trade_name %></dd>
  <dt>Domínio dos e-mails:</dt>
  <dd><%= @shipping_company.domain_name %></dd>
  <dt>CNPJ:</dt>
  <dd><%= @shipping_company.cnpj %></dd>
  <dt>Endereço faturamento:</dt>
  <dd><%= @shipping_company.billing_address %></dd>
  <dt>Status:</dt>
  <dd><%= @shipping_company.active %></dd>
</dl>